### ISSUE TITLE
banklogs are updated

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [snesrev/sm#10]
time to rename some functions...

banklogs here: (delete browser cache)
https://patrickjohnston.org/bank/index.html

**Comment by H-A-M-G-E-R** [comment]
also, in https://patrickjohnston.org/ASM/ROM%20data/Super%20Metroid/SPC%20disassembly.asm, death beam is called 'ketchup beam'

**Comment by snesrev** [comment]
Thanks for the info, will have a look at it at some point.
