### ISSUE TITLE
Document SDL dependencies

### ISSUE THREAD

**Issue by gamedevsam** [snesrev/sm#15]
I tried to compile this and ran into this error:

```bash
make: sdl2-config: Command not found
make: sdl2-config: Command not found
cc -c -O2 -Werror   -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 -I. src/config.c -o src/config.o
In file included from src/config.c:1:
src/config.h:3:10: fatal error: 'SDL_keycode.h' file not found
#include <SDL_keycode.h>
```

**Comment by gamedevsam** [comment]
I was able to compile the app on my Macbook M1 by installing SDL with the following commands:

```bash
brew install SDL2

brew install SDL2_image

brew install SDL2_ttf
```

Not sure all of these are required, but I didn't want to mess with it too much.

Then I could run the app like so:

```bash
make

./sm
```

**Comment by DaBanana64** [comment]
I've made a build instructions (#7) it has all the necessary installations for dependencies. Hopefully snesrev merges it.

**Comment by dagit** [comment]
@gamedevsam Looks like #7 was merged. Does that give you the documentation you need? I suspect this ticket can be closed now.

**Comment by gamedevsam** [comment]
Yessir, thank you for the docs!
