### ISSUE TITLE
Game crashing on Launch "Verify Failure"

### ISSUE THREAD

**Issue by Ash-Hybrid** [snesrev/sm#8]
Loading the game is impossible and it closes immediately, the console mentions assertion failure on line 497 for one of the files. (i am unsure if this similar to another issue that is on here, as the amount of times ive attempted launching it has gained 0 results so far, so im guessing whatever issue i am having is probably different and could possibly be on my own end..? I am unsure).
Here is the image of what is mentioned  in the console:
![Verify Failure](https://user-images.githubusercontent.com/117756404/223790190-dcadc9bc-6279-420a-b138-0e78d1d87634.PNG)

**Comment by FitzRoyX** [comment]
Post your rom hash pls

**Comment by Ash-Hybrid** [comment]
No-Intro Name: Super Metroid (Europe) (En,Fr,De)
(No-Intro version  20130701-030720)
File SHA-1: 01C41AE38094458B11B84F2025570C93DAD8E662
ROM SHA-1: 082ADAC9E38F86240F4378A6AA400DEE1716AE87

**Comment by FitzRoyX** [comment]
That's the pal 50fps rom, you need to feed it the USA/JPN rom with the hash given in the readme.

**Comment by Ash-Hybrid** [comment]
got it, thanks for the information.
